# Generated by Django 3.0.7 on 2020-06-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='downvotes',
            new_name='results',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
    ]
